## NumPy 
판다스
```
넘파이 숫자 선형대수 행렬연산 핵심
#📌 python 의 array와 다름
import array
```

In [14]:
import numpy as np

리스트 = [1,2,3,4,5]

넘파이객체 = np.array(리스트)
넘파이객체
print(f"넘파이객체 - {넘파이객체}", f"\n", f"타입 - {type(넘파이객체)}")

넘파이객체 - [1 2 3 4 5] 
 타입 - <class 'numpy.ndarray'>


## 파이썬이 제공하는 pprint와는 다른 사용자 함수 정의

In [32]:
# 사용자함수 정의
def pprint(arr: np.ndarray):
    print(f"type: {type(arr)}")
    print(f"shape: {arr.shape}")
    print(f"ndim: {arr.ndim}")
    print(f"dtype: {arr.dtype}")

In [28]:
pprint(넘파이객체)

type:<class 'numpy.ndarray'>
shape: (5,)
ndim: 1
dtype: int64


In [30]:
print(넘파이객체)

[1 2 3 4 5]


In [ ]:
리스트 = [1,2,3,4,5]
넘파이객체 = np.array(리스트, dtype='float64')
pprint(넘파이객체)

type: <class 'numpy.ndarray'>
shape: (5,)
ndim: 1
dtype: float64


In [35]:
arr2 = [(1,2,3), (4,5,6)]
a2 = np.array(arr2, dtype=float)
pprint(a2)

type: <class 'numpy.ndarray'>
shape: (2, 3)
ndim: 2
dtype: float64



### 파이썬 3차원 배열로 NumPy 배열 생성, 원소 데이터 타입 지정

In [49]:
arr = np.array([[[1,2,3], [4,5,6]], [[3,2,1], [4,5,6]]], dtype = float)
a = np.array(arr, dtype = float)
pprint(a)
a

type: <class 'numpy.ndarray'>
shape: (2, 2, 3)
ndim: 3
dtype: float64


array([[[1., 2., 3.],
        [4., 5., 6.]],

       [[3., 2., 1.],
        [4., 5., 6.]]])

In [42]:
a = np.ones((2,3,4), dtype = np.int16)
pprint(a)
a

type: <class 'numpy.ndarray'>
shape: (2, 3, 4)
ndim: 3
dtype: int16


array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [44]:
a = np.zeros((3,4), dtype = np.int16)
pprint(a)
a

type: <class 'numpy.ndarray'>
shape: (3, 4)
ndim: 2
dtype: int16


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [50]:
a = np.eye(4, dtype = np.float64)
pprint(a)
a

type: <class 'numpy.ndarray'>
shape: (4, 4)
ndim: 2
dtype: float64


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [52]:
a = np.empty((4,2), dtype = np.float64)
pprint(a)
a

type: <class 'numpy.ndarray'>
shape: (4, 2)
ndim: 2
dtype: float64


array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [54]:
a = np.empty((4,2))
pprint(a)
a

type: <class 'numpy.ndarray'>
shape: (4, 2)
ndim: 2
dtype: float64


array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

# 2.3 데이터 생성 함수
```
# NumPy는 주어진 조건으로 데이터를 생성한 후, 배열을 만드는 데이터 생성 함수를 제공합니다.
# numpy.linspace
# numpy.arange
# numpy.logspace
# np.linspace 함수
```

In [56]:
aa = np.linspace(1, 100, num=50, endpoint=True, retstep=False, dtype=None)
pprint(aa)
aa

type: <class 'numpy.ndarray'>
shape: (50,)
ndim: 1
dtype: float64


array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])